ktor {
    development = false
    deployment {
        port = 8080
        port = ${?PORT}
        watch = [ classes, resources ]
    }
    application {
        modules = [com.guesswhosesong.server.ApplicationKt.module]
    }
}

redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}
}

spotify {
    clientId = ${?SPOTIFY_CLIENT_ID}
    clientSecret = ${?SPOTIFY_CLIENT_SECRET}
    redirectUri = ${?SPOTIFY_REDIRECT_URI}
}
